/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Skript47 (https://sketchfab.com/Skript47)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-monitor-169-low-poly-game-ready-336de680dd9a4d84943d05d9c7dde1b0
Title: Computer Monitor 16:9 (Low Poly, Game Ready)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model2 = (props) => {
  const { nodes, materials } = useGLTF('/computer_monitor_169_low_poly_game_ready.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Monitor_01_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Monitor_01_B}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/computer_monitor_169_low_poly_game_ready.glb')

export default Model2;

